spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pre_order
    username: hanghae
    password: hanghae
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

  data:
    redis:
      port: 6379
      host: localhost

  mail:
    host: smtp.google.com #smtp ?? ??
    port: 587 # ?? ???? ??(??? 587?)
    username: cod2048@gmail.com #?? ???
    password: ${EMAIL_PASSWORD} #?? ????
    auth-code-expiration-millis: 600000
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
#          ssl:
#            #trust: smtp.naver.com
#            enable: true #??? ?? -> SSL ??? ?????